# Generated by Django 4.1.3 on 2023-01-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(default='1', primary_key=True, serialize=False)),
                ('patient_name', models.CharField(default='', max_length=200)),
                ('patient_mob_no', models.CharField(default='', max_length=200)),
                ('patient_email', models.EmailField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_detail', models.CharField(max_length=200)),
                ('product_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_present', models.IntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bills.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cust_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(verbose_name='purchased date')),
                ('total_items', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.patient')),
            ],
        ),
    ]
